### ISSUE TITLE
Setting Angle of wheel

### ISSUE THREAD

**Issue by reinzor** [ForestMist/logitech-g29#2]
Hi @ForestMist ,

I'm trying to create a controller that sets the wheel to a specific angle. However, I am playing with the force API as specified here:

https://github.com/ForestMist/logitech-g29/blob/master/docs/api.md#force

but I am not able to do this. I also looked at your autoCenter function but this does not allow setting the reference angle.

Is this possible? Thanks

**Comment by ForestMist** [comment]
It would be super neat if there was a low level command that could be sent directly to the wheel to set a position. If there were, I would love to write a wrapper for it but unfortunately I don't know if that feature exists or where it may be documented. I'm all ears if anyone knows more about this.

Luckily, we can simulate a move with what is probably 'close enough' accuracy depending on your needs.

```js
var g = require('logitech-g29')

var options = {
    autocenter: false, // set to false so the wheel will not fight itself when we rotate it
    debug: false,
    range: 900
}

var wheel = {
    currentPos: 0, // initial value does not matter
    moveToPos: 0,  // initial value does not matter
    moved: true
}

function moveToDegree(deg) {
    /*
    @param  {Number}  deg  Degree can be anywhere from 0 (far left) to 450 (center) to 900 (far right).
    */
    deg = deg / options.range * 100

    wheel.moveToPos = deg
    wheel.moved = false

    if (deg < wheel.currentPos) {
        g.forceConstant(0.3)
    } else {
        g.forceConstant(0.7)
    }
}

g.connect(options, function(err) {
    if (err) {
        console.log('Oops -> ' + err)
    }

    g.forceFriction(0.6) // without friction the wheel will tend to overshoot a move command

    moveToDegree(options.range / 2) // center

    g.on('wheel-turn', function(val) {
        wheel.currentPos = val

        if (wheel.moved === false) {
            console.log('wheel at position ' + val)

            var min = wheel.moveToPos - 1
            var max = wheel.moveToPos + 1

            if (wheel.currentPos >= min && wheel.currentPos <= max) {
                console.log('--- move complete, turning off force')
                g.forceConstant() // turn off force
                wheel.moved = true
            }
        }
    })
})
```

I recommend placing the above code in a file like `test.js`. Then you can run `node` interactively and load that file into the REPL using `.load test.js`. If you have any wheel connecting issues, wait a few moments and then try the same procedure again.

Once the REPL is happy, try using the `moveToDegree()` function to see how it works. For example, `moveToDegree(360)` will be 90 degrees left and `moveToDegree(540)` will be 90 degrees right. Try any degree from 0 (far left) to 900 (far right).

The key elements to get this setup working seem to be...

- Turn off auto centering.
- Use an appropriate `g.forceConstant(x)` speed to move left or right. The slower you move, the more accurate the final position should be.
- Set a bit of `g.forceFriction(x)` so the wheel does not keep rotating after reaching a position.

I hope that by mixing `g.forceConstant(x)` and `g.forceFriction(x)` you'll be able to find a setting that will work for your project. *fingers crossed*

**Comment by reinzor** [comment]
I tried your approach; implementing a 'regular P controller' works better with some friction:

<code>
var g = require('logitech-g29')

var options = {
    autocenter: false, // set to false so the wheel will not fight itself when we rotate it
    debug: false,
    range: 900
}

var wheel = {
    currentPos: 0, // initial value does not matter
    moveToPos: 0,  // initial value does not matter
    moved: true
}

function moveToDegree(deg) {
    /*
    @param  {Number}  deg  Degree can be anywhere from 0 (far left) to 450 (center) to 900 (far right).
    */
    deg = deg / options.range * 100

    wheel.moveToPos = deg
    wheel.moved = false

    if (deg < wheel.currentPos) {
        g.forceConstant(0.3)
    } else {
        g.forceConstant(0.7)
    }
}

var connected = false;
var setpoint = 50;
setInterval(function() { 
    if (!connected)
        return;

    var seconds = new Date().getTime() / 1000;
    setpoint = 50 + 10 * Math.sin(seconds);

    var error = setpoint - wheel.currentPos;
    console.log("Setpoint:", setpoint);
    console.log("Position:", wheel.currentPos);
    console.log("Error:", error);

    var p = 0.1;
    var u = p * error; // u may range from -0.5 to 0.5

    var u_clipped = Math.max(-0.5, Math.min(0.5, u));

    console.log("U, U clipped", u, u_clipped);

    g.forceConstant(0.5 + u_clipped);

}, 100);

g.connect(options, function(err) {
    if (err) {
        console.log('Oops -> ' + err)
    }
    connected = true;

    g.forceFriction(0.8) // without friction the wheel will tend to overshoot a move command

    g.on('wheel-turn', function(val) {
        wheel.currentPos = val;
    })
})
</code>

**Comment by ForestMist** [comment]
Ah, so it slows down as it nears a final degree? Neat.

Is the new code going to work for your project? Oh and if you don't mind... what is your project? Doing something interesting with a Logitech wheel no doubt. :D

**Comment by reinzor** [comment]
Yes, I might implement a proper controller if I have time. I also see that it has some friction so some feed forward can be applied to overcome this. 

We are working on a driving simulator where the steering wheel can be actuated by a third party application.

This approach suits for me :). Thanks for your quick feedback! I can make a pull request with this feature as api when I have a proper controller for this, might this be an idea?

-Rein

**Comment by ForestMist** [comment]
Neat, very happy it worked out. :D

Since moving the wheel to a certain location requires changing multiple parameters, I'm not sure I would want to add it as an API method. The technique is super useful though so I'm glad it is detailed here. Thanks for posting this issue.

Once your project is done I would be happy to post about it on Facebook, Twitter, etc... so feel free to let me know if / when you want me to get the word out. :D

Going to close this issue since there is nothing I currently want to add to the library BUT... once again, thank you for opening this. I'm sure this issue will be useful to others looking to accomplish a servo like move.

Cheers!
