### ISSUE TITLE
Wheel keeps spinning on Windows

### ISSUE THREAD

**Issue by francisco76** [ForestMist/logitech-g29#4]
Hello,

As soon as I run the test programm and touch any button or move the wheel it starts spinning all the way right and stays there.Have you had this problem before, or do you know how to fix it?

Thank you.

**Comment by ForestMist** [comment]
Ooh it could be the platform switch which is located on the top of the wheel center. Try setting it to PS3 if it isn't already. The opposite position of what the image shows below.

![platform-switch](https://user-images.githubusercontent.com/1933203/27483969-5452bd9c-57dc-11e7-9dc3-f65912d74b31.jpg)

If that doesn't do the trick, please let me know.

**Comment by francisco76** [comment]
It is on ps3 mode, but still when I run any code using the library on windows is just goes all the way right, on linux or mac works perfectly tough.

**Comment by STshaimagz** [comment]
Hello, I have exactly the same issue. I tried to turn it to PS3/PS4 and both don't work on Windows 10.
Can help with debugging if you need. Need an urgent solution...

**Comment by ForestMist** [comment]
Sorry the delay. I will pull my G29 out of storage and hook it up to my Windows 10 PC to see if I can get the same issue.

**Comment by francisco76** [comment]
Thank you Daniel, that would be helpful.

2017-06-27 15:54 GMT-07:00 Daniel Gagan <notifications@github.com>:

**Comment by STPA17** [comment]
I investigated a bit more and it seems like none of the device.write functions work but I can listen to the events perfectly. So first, the device turns all the way to the right side, when I try to center it or even turn on the LEDs it won't get these commands or display any error at all. I also tried the relay function and it doesn't work. The 'change' event and other listeners are good.
The issue is with writing only.

There are also sometimes when it's not connected even after disconnecting before the end of the session but that's a separate issue which I don't think is related to this one.

**Comment by ForestMist** [comment]
Quick update.

Ooh yeah. The device.write is not making it through. Thanks for spotting that. 

I have the same exact issue on my Windows 10 machine. Different versions of node or node-hid do not seem to make a difference.

What is interesting is the list o' devices I get back from node-hid. Three of the them match the criteria that this library is looking for. The first match is the one the library hooks onto and it along with the second entry both get errors when using device.write.

Entry three will accept writes but it seems to just rotate the wheel slowly the right.... unless you prepend the command with a 0x00 that is! Then the wheel does what you expect which in my case was to turn on all the LEDs. I found the 0x00 trick via a random Google search and it seems to be something that is only necessary in Windows. Detecting the OS will be easy and can be added to the library to use as needed.

Figuring out how to reliably detect which one of the three G29 device paths is where I am now. Will let you know as soon as I have more info or anything to test with.

P.S. - Francisco, apparently we both know Peter who I was reaching out to for info earlier today. Hehe.

**Comment by ForestMist** [comment]
Sure thing. ^_^ 

Fresh code ready for testing at https://github.com/ForestMist/logitech-g29/tree/windows-10

Should work on Mac, Linux, and Windows. Feel free to give it a whirl and let me know what you find.

**Comment by STPA17** [comment]
That works great! It also fixed the issue on Mac when sometimes it won't connect and had to try multiple times. Thanks Daniel, this was fast and cross platform fix.
I'm having another issue with the accuracy of the movement but it might be my code, I'll check that tomorrow and let you know if there are any problems.

**Comment by ForestMist** [comment]
Sweet. Thanks for the update. :)

I am curious about the accuracy thingy. I just learned recently that the G29 reports with more fidelity than the older G27 but if there is something software wise we can do for more accuracy, I'm all for it.

**Comment by ForestMist** [comment]
Latest code that fixes this issue is now live on GitHub and NPM.

Thank you both for making this library better. ^_^
